export enum RouterContrains {
    // eslint-disable-next-line @typescript-eslint/naming-convention
    INICIO = 'inicio',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    LOGIN_ADMIN = 'login-admin',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    LOGIN_USER = 'login-usuario',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CREAR_CLIENTE = '/crear-cliente',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CREAR_PEDIDO = '/crear-pedido',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CREAR_PRENDA = '/crear-prenda',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CREAR_REFERENCIA = '/crear-referencia',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CONSULTAR_PEDIDO = '/consultar-pedido',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    CONSULTAR_PEDIDO_ADMIN = '/consultar-pedido-admin',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    MODIFICAR_PEDIDO = '/modificar-pedido',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    MODIFICAR_PEDIDO_ADMIN = '/modificar-pedido-admin',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    OPERADORES = 'operadores/',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    TABS = '/tabs/tab2',
    // eslint-disable-next-line @typescript-eslint/naming-convention
    PROCESO_PEDIDO = '/proceso-pedido',
    // eslint-disable-next-line @typescript-eslint/naming-convention
};
